/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetEffectiveConfigParams,
  GetInfo12PathParameters,
  HistoryListParams,
  HistoryPathParameters,
  List14Params,
  Remove10Params,
  TableDataInfo,
  TravelAlgorithmConfig
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 新增算法配置
 */
const add2 = (
    travelAlgorithmConfig: TravelAlgorithmConfig,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/algorithm/config`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelAlgorithmConfig
    },
      );
    }
  /**
 * @summary 删除算法配置
 */
const remove10 = (
    params: Remove10Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/algorithm/config/remove`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 修改算法配置
 */
const edit14 = (
    travelAlgorithmConfig: TravelAlgorithmConfig,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/algorithm/config/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelAlgorithmConfig
    },
      );
    }
  /**
 * @summary 查询配置详情
 */
const getInfo12 = (
    { configId }: GetInfo12PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/algorithm/config/${configId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 分页查询算法配置列表
 */
const list14 = (
    params: List14Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/algorithm/config/list`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary 查询配置历史
 */
const history = (
    { configId }: HistoryPathParameters,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/algorithm/config/history/${configId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 分页查询配置历史
 */
const historyList = (
    params: HistoryListParams,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/algorithm/config/history/list`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary 查询生效配置
 */
const getEffectiveConfig = (
    params?: GetEffectiveConfigParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/algorithm/config/effective`, method: 'GET',
        params
    },
      );
    }
  return {add2,remove10,edit14,getInfo12,list14,history,historyList,getEffectiveConfig}};
export type Add2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add2']>>>
export type Remove10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove10']>>>
export type Edit14Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit14']>>>
export type GetInfo12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo12']>>>
export type List14Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list14']>>>
export type HistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['history']>>>
export type HistoryListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['historyList']>>>
export type GetEffectiveConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getEffectiveConfig']>>>
