/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, GetByTypePathParameters } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 批量查询多个字典类型
   */
  const getBatch = (getBatchBody: string[]) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/dict/batch`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getBatchBody,
    });
  };
  /**
   * @summary 根据字典类型查询字典数据
   */
  const getByType = ({ dictType }: GetByTypePathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/dict/${dictType}`, method: 'GET' });
  };
  /**
   * @summary 获取字典类型列表
   */
  const getTypes = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/dict/types`, method: 'GET' });
  };
  return { getBatch, getByType, getTypes };
};
export type GetBatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getBatch']>>>;
export type GetByTypeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getByType']>>>;
export type GetTypesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getTypes']>>>;
