/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, UnlockScreenBody } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getSysIndexController = () => {
  const unlockScreen = (unlockScreenBody: UnlockScreenBody) => {
    return orvalMutator<AjaxResult>({
      url: `/unlockscreen`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: unlockScreenBody,
    });
  };
  const index = () => {
    return orvalMutator<string>({ url: `/`, method: 'GET' });
  };
  const index3 = () => {
    return orvalMutator<string>({ url: `/`, method: 'PUT' });
  };
  const index2 = () => {
    return orvalMutator<string>({ url: `/`, method: 'POST' });
  };
  const index5 = () => {
    return orvalMutator<string>({ url: `/`, method: 'DELETE' });
  };
  const index1 = () => {
    return orvalMutator<string>({ url: `/`, method: 'HEAD' });
  };
  const index4 = () => {
    return orvalMutator<string>({ url: `/`, method: 'PATCH' });
  };
  return { unlockScreen, index, index3, index2, index5, index1, index4 };
};
export type UnlockScreenResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['unlockScreen']>>
>;
export type IndexResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index']>>
>;
export type Index3Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index3']>>
>;
export type Index2Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index2']>>
>;
export type Index5Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index5']>>
>;
export type Index1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index1']>>
>;
export type Index4Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysIndexController>['index4']>>
>;
