/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  Add6Params,
  AjaxResult,
  Edit6Params,
  GetInfo18PathParameters,
  List18Params,
  MarkReadAllParams,
  MarkReadParams,
  Remove17PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改通知公告
   */
  const edit6 = (params?: Edit6Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice`, method: 'PUT', params });
  };
  /**
   * @summary 新增通知公告
   */
  const add6 = (params?: Add6Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice`, method: 'POST', params });
  };
  /**
   * @summary 标记公告已读
   */
  const markRead = (params: MarkReadParams) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice/markRead`, method: 'POST', params });
  };
  /**
   * @summary 批量标记已读
   */
  const markReadAll = (params: MarkReadAllParams) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice/markReadAll`, method: 'POST', params });
  };
  /**
   * @summary 根据通知公告编号获取详细信息
   */
  const getInfo18 = ({ noticeId }: GetInfo18PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice/${noticeId}`, method: 'GET' });
  };
  /**
   * @summary 获取通知公告列表
   */
  const list18 = (params?: List18Params) => {
    return orvalMutator<TableDataInfo>({ url: `/system/notice/list`, method: 'GET', params });
  };
  /**
   * @summary 首页顶部公告列表
   */
  const listTop = () => {
    return orvalMutator<AjaxResult>({ url: `/system/notice/listTop`, method: 'GET' });
  };
  /**
   * @summary 删除通知公告
   */
  const remove17 = ({ noticeIds }: Remove17PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/notice/${noticeIds}`, method: 'DELETE' });
  };
  return { edit6, add6, markRead, markReadAll, getInfo18, list18, listTop, remove17 };
};
export type Edit6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit6']>>>;
export type Add6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add6']>>>;
export type MarkReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['markRead']>>>;
export type MarkReadAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['markReadAll']>>
>;
export type GetInfo18Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo18']>>>;
export type List18Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list18']>>>;
export type ListTopResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['listTop']>>>;
export type Remove17Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove17']>>>;
