/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo7PathParameters,
  List18Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询景点详情（含图片）
 */
const getInfo7 = (
    { attractionId }: GetInfo7PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/attraction/${attractionId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询景点列表
 */
const list18 = (
    params?: List18Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/attraction/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo7,list18}};
export type GetInfo7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo7']>>>
export type List18Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list18']>>>
