/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, GetInfo5PathParameters, List15Params } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getC = () => {
  /**
   * @summary 查询景点详情（含图片）
   */
  const getInfo5 = ({ attractionId }: GetInfo5PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/attraction/${attractionId}`, method: 'GET' });
  };
  /**
   * @summary 查询景点列表
   */
  const list15 = (params?: List15Params) => {
    return orvalMutator<AjaxResult>({ url: `/wx/attraction/list`, method: 'GET', params });
  };
  return { getInfo5, list15 };
};
export type GetInfo5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo5']>>>;
export type List15Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list15']>>>;
