/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  RegisterBody
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysRegisterController = () => {
const register = (
    registerBody: RegisterBody,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerBody
    },
      );
    }
  return {register}};
export type RegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysRegisterController>['register']>>>
