/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, RegisterParams } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getSysRegisterController = () => {
  const register = (params?: RegisterParams) => {
    return orvalMutator<AjaxResult>({ url: `/register`, method: 'POST', params });
  };
  return { register };
};
export type RegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysRegisterController>['register']>>
>;
