/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddSave7Params,
  AjaxResult,
  CheckinListPathParameters,
  EditSave7Params,
  Export6Params,
  GetInfo11PathParameters,
  List7Params,
  Remove9Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 删除景点
   */
  const remove9 = (params: Remove9Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/attraction/remove`, method: 'POST', params });
  };
  /**
   * @summary 查询景点列表
   */
  const list7 = (params: List7Params) => {
    return orvalMutator<TableDataInfo>({
      url: `/travel18/attraction/list`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 导出景点列表
   */
  const export6 = (params: Export6Params) => {
    return orvalMutator<void>({ url: `/travel18/attraction/export`, method: 'POST', params });
  };
  /**
   * @summary 修改保存景点
   */
  const editSave7 = (params: EditSave7Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/attraction/edit`, method: 'POST', params });
  };
  /**
   * @summary 新增保存景点
   */
  const addSave7 = (params: AddSave7Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/attraction/add`, method: 'POST', params });
  };
  /**
   * @summary 查询景点详情
   */
  const getInfo11 = ({ attractionId }: GetInfo11PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/attraction/${attractionId}`, method: 'GET' });
  };
  /**
   * @summary 查询景点下的打卡点列表
   */
  const checkinList = ({ attractionId }: CheckinListPathParameters) => {
    return orvalMutator<AjaxResult>({
      url: `/travel18/attraction/checkin/${attractionId}`,
      method: 'GET',
    });
  };
  return { remove9, list7, export6, editSave7, addSave7, getInfo11, checkinList };
};
export type Remove9Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove9']>>>;
export type List7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list7']>>>;
export type Export6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export6']>>>;
export type EditSave7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave7']>>>;
export type AddSave7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave7']>>>;
export type GetInfo11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo11']>>>;
export type CheckinListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['checkinList']>>
>;
