/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export16Params,
  List35Params,
  Remove25PathParameters,
  TableDataInfo,
  Unlock1PathParameters
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysLogininforController = () => {
const export16 = (
    params: Export16Params,
 ) => {
      return orvalMutator<void>(
      {url: `/monitor/logininfor/export`, method: 'POST',
        params
    },
      );
    }
  const unlock1 = (
    { userName }: Unlock1PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/unlock/${userName}`, method: 'GET'
    },
      );
    }
  const list35 = (
    params: List35Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/monitor/logininfor/list`, method: 'GET',
        params
    },
      );
    }
  const remove25 = (
    { infoIds }: Remove25PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/${infoIds}`, method: 'DELETE'
    },
      );
    }
  const clean1 = (

 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/clean`, method: 'DELETE'
    },
      );
    }
  return {export16,unlock1,list35,remove25,clean1}};
export type Export16Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['export16']>>>
export type Unlock1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['unlock1']>>>
export type List35Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['list35']>>>
export type Remove25Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['remove25']>>>
export type Clean1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['clean1']>>>
