/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export15Params,
  List26Params,
  Remove24PathParameters,
  TableDataInfo,
  UnlockPathParameters
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysLogininforController = () => {
const export15 = (
    params: Export15Params,
 ) => {
      return orvalMutator<void>(
      {url: `/monitor/logininfor/export`, method: 'POST',
        params
    },
      );
    }
  const unlock = (
    { userName }: UnlockPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/unlock/${userName}`, method: 'GET'
    },
      );
    }
  const list26 = (
    params: List26Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/monitor/logininfor/list`, method: 'GET',
        params
    },
      );
    }
  const remove24 = (
    { infoIds }: Remove24PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/${infoIds}`, method: 'DELETE'
    },
      );
    }
  const clean1 = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/logininfor/clean`, method: 'DELETE'
    },
      );
    }
  return {export15,unlock,list26,remove24,clean1}};
export type Export15Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['export15']>>>
export type UnlockResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['unlock']>>>
export type List26Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['list26']>>>
export type Remove24Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['remove24']>>>
export type Clean1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysLogininforController>['clean1']>>>
