/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  Add9Params,
  AjaxResult,
  DictTypePathParameters,
  Edit9Params,
  Export12Params,
  GetInfo21PathParameters,
  List21Params,
  Remove20PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改保存字典类型
   */
  const edit9 = (params?: Edit9Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/data`, method: 'PUT', params });
  };
  /**
   * @summary 新增字典类型
   */
  const add9 = (params?: Add9Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/data`, method: 'POST', params });
  };
  /**
   * @summary 导出字典数据
   */
  const export12 = (params?: Export12Params) => {
    return orvalMutator<void>({ url: `/system/dict/data/export`, method: 'POST', params });
  };
  /**
   * @summary 查询字典数据详细
   */
  const getInfo21 = ({ dictCode }: GetInfo21PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/data/${dictCode}`, method: 'GET' });
  };
  /**
   * @summary 根据字典类型查询字典数据信息
   */
  const dictType = ({ dictType }: DictTypePathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/data/type/${dictType}`, method: 'GET' });
  };
  /**
   * @summary 获取字典数据列表
   */
  const list21 = (params?: List21Params) => {
    return orvalMutator<TableDataInfo>({ url: `/system/dict/data/list`, method: 'GET', params });
  };
  /**
   * @summary 删除字典类型
   */
  const remove20 = ({ dictCodes }: Remove20PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/data/${dictCodes}`, method: 'DELETE' });
  };
  return { edit9, add9, export12, getInfo21, dictType, list21, remove20 };
};
export type Edit9Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit9']>>>;
export type Add9Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add9']>>>;
export type Export12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export12']>>>;
export type GetInfo21Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo21']>>>;
export type DictTypeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['dictType']>>>;
export type List21Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list21']>>>;
export type Remove20Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove20']>>>;
