/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo2PathParameters,
  List12Params
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 获取地方特色菜详情
 */
const getInfo2 = (
    { specialtyId }: GetInfo2PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/localSpecialty/${specialtyId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 按省市区查询地方特色菜列表
 */
const list12 = (
    params?: List12Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/localSpecialty/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo2,list12}};
export type GetInfo2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo2']>>>
export type List12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list12']>>>
