/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, GetInfo1PathParameters, List11Params } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 获取地方特色菜详情
   */
  const getInfo1 = ({ specialtyId }: GetInfo1PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/localSpecialty/${specialtyId}`, method: 'GET' });
  };
  /**
   * @summary 按省市区查询地方特色菜列表
   */
  const list11 = (params?: List11Params) => {
    return orvalMutator<AjaxResult>({ url: `/wx/localSpecialty/list`, method: 'GET', params });
  };
  return { getInfo1, list11 };
};
export type GetInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo1']>>>;
export type List11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list11']>>>;
