/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo19PathParameters,
  List19Params,
  Remove18PathParameters,
  RoleMenuTreeselectPathParameters,
  SysMenu,
  TreeselectParams,
  UpdateSortBody
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 修改菜单
 */
const edit7 = (
    sysMenu: SysMenu,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sysMenu
    },
      );
    }
  /**
 * @summary 新增菜单
 */
const add7 = (
    sysMenu: SysMenu,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sysMenu
    },
      );
    }
  /**
 * @summary 保存菜单排序
 */
const updateSort = (
    updateSortBody: UpdateSortBody,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/updateSort`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSortBody
    },
      );
    }
  /**
 * @summary 根据菜单编号获取详细信息
 */
const getInfo19 = (
    { menuId }: GetInfo19PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/${menuId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 删除菜单
 */
const remove18 = (
    { menuId }: Remove18PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/${menuId}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary 获取菜单下拉树列表
 */
const treeselect = (
    params: TreeselectParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/treeselect`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary 加载对应角色菜单列表树
 */
const roleMenuTreeselect = (
    { roleId }: RoleMenuTreeselectPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/roleMenuTreeselect/${roleId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 获取菜单列表
 */
const list19 = (
    params: List19Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/menu/list`, method: 'GET',
        params
    },
      );
    }
  return {edit7,add7,updateSort,getInfo19,remove18,treeselect,roleMenuTreeselect,list19}};
export type Edit7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit7']>>>
export type Add7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add7']>>>
export type UpdateSortResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['updateSort']>>>
export type GetInfo19Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo19']>>>
export type Remove18Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove18']>>>
export type TreeselectResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['treeselect']>>>
export type RoleMenuTreeselectResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['roleMenuTreeselect']>>>
export type List19Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list19']>>>
