/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getServerController = () => {
const getInfo30 = (

 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/server`, method: 'GET'
    },
      );
    }
  return {getInfo30}};
export type GetInfo30Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getServerController>['getInfo30']>>>
