/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getServerController = () => {
  const getInfo24 = () => {
    return orvalMutator<AjaxResult>({ url: `/monitor/server`, method: 'GET' });
  };
  return { getInfo24 };
};
export type GetInfo24Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getServerController>['getInfo24']>>
>;
