/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo9PathParameters,
  List5Params,
  Remove7Params,
  TableDataInfo,
  TravelCheckin
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 删除打卡点
 */
const remove7 = (
    params: Remove7Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/checkin/remove`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 查询打卡点列表
 */
const list5 = (
    params: List5Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/checkin/list`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 修改保存打卡点
 */
const editSave5 = (
    travelCheckin: TravelCheckin,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/checkin/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelCheckin
    },
      );
    }
  /**
 * @summary 新增保存打卡点
 */
const addSave6 = (
    travelCheckin: TravelCheckin,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/checkin/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelCheckin
    },
      );
    }
  /**
 * @summary 查询打卡点详情
 */
const getInfo9 = (
    { checkinId }: GetInfo9PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/checkin/${checkinId}`, method: 'GET'
    },
      );
    }
  return {remove7,list5,editSave5,addSave6,getInfo9}};
export type Remove7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove7']>>>
export type List5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list5']>>>
export type EditSave5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave5']>>>
export type AddSave6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave6']>>>
export type GetInfo9Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo9']>>>
