/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddCarPathParameters,
  AddPhotographyPathParameters,
  AjaxResult,
  AutoGenerateParams,
  ConfirmParams,
  ConfirmStatusParams,
  CopyParams,
  Edit12Params,
  GetInfo1PathParameters,
  RemoveParams,
  UpdateDayAccommodationPathParameters,
  UpdateDayAttractionsPathParameters,
  UpdateDayDiningParams,
  UpdateDayDiningPathParameters,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getC = () => {
  /**
   * @summary 添加行程跟拍
   */
  const addPhotography = (
    { itineraryId }: AddPhotographyPathParameters,
    addPhotographyBody: number,
  ) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/itinerary/${itineraryId}/photography/add`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addPhotographyBody,
    });
  };
  /**
   * @summary 更新日程餐饮
   */
  const updateDayDining = (
    { itineraryId, dayNumber }: UpdateDayDiningPathParameters,
    params?: UpdateDayDiningParams,
  ) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/dining`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 更新日程景点
   */
  const updateDayAttractions = (
    { itineraryId, dayNumber }: UpdateDayAttractionsPathParameters,
    updateDayAttractionsBody: string,
  ) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/attractions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateDayAttractionsBody,
    });
  };
  /**
   * @summary 更新日程住宿
   */
  const updateDayAccommodation = (
    { itineraryId, dayNumber }: UpdateDayAccommodationPathParameters,
    updateDayAccommodationBody: number,
  ) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/accommodation`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: updateDayAccommodationBody,
    });
  };
  /**
   * @summary 添加行程包车
   */
  const addCar = ({ itineraryId }: AddCarPathParameters, addCarBody: number) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/itinerary/${itineraryId}/car/add`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCarBody,
    });
  };
  /**
   * @summary 删除行程
   */
  const remove = (params?: RemoveParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/remove`, method: 'POST', params });
  };
  /**
   * @summary 修改行程
   */
  const edit12 = (params?: Edit12Params) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/edit`, method: 'POST', params });
  };
  /**
   * @summary 复制行程
   */
  const copy = (params?: CopyParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/copy`, method: 'POST', params });
  };
  /**
   * @summary 确认行程
   */
  const confirm = (params?: ConfirmParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/confirm`, method: 'POST', params });
  };
  /**
   * @summary 更新确认状态
   */
  const confirmStatus = (params?: ConfirmStatusParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/confirmStatus`, method: 'POST', params });
  };
  /**
   * @summary 一键生成行程
   */
  const autoGenerate = (params?: AutoGenerateParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/auto`, method: 'POST', params });
  };
  /**
   * @summary 查询行程详情
   */
  const getInfo1 = ({ itineraryId }: GetInfo1PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/${itineraryId}`, method: 'GET' });
  };
  /**
   * @summary 查询行程列表
   */
  const list10 = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/itinerary/list`, method: 'GET' });
  };
  return {
    addPhotography,
    updateDayDining,
    updateDayAttractions,
    updateDayAccommodation,
    addCar,
    remove,
    edit12,
    copy,
    confirm,
    confirmStatus,
    autoGenerate,
    getInfo1,
    list10,
  };
};
export type AddPhotographyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['addPhotography']>>
>;
export type UpdateDayDiningResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['updateDayDining']>>
>;
export type UpdateDayAttractionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['updateDayAttractions']>>
>;
export type UpdateDayAccommodationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['updateDayAccommodation']>>
>;
export type AddCarResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['addCar']>>>;
export type RemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['remove']>>>;
export type Edit12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['edit12']>>>;
export type CopyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['copy']>>>;
export type ConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['confirm']>>>;
export type ConfirmStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['confirmStatus']>>
>;
export type AutoGenerateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getC>['autoGenerate']>>
>;
export type GetInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo1']>>>;
export type List10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list10']>>>;
