/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddCarPathParameters,
  AddPhotographyPathParameters,
  AjaxResult,
  GetInfo3PathParameters,
  List13Params,
  RemoveDayAccommodationPathParameters,
  RemoveDayCarPathParameters,
  RemoveDayDiningParams,
  RemoveDayDiningPathParameters,
  RemoveDayPhotographyPathParameters,
  TravelItinerary,
  TravelItineraryDining,
  UpdateDayAccommodationPathParameters,
  UpdateDayAttractions1Params,
  UpdateDayAttractions1PathParameters,
  UpdateDayAttractionsParams,
  UpdateDayAttractionsPathParameters,
  UpdateDayDiningPathParameters
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 删除日程跟拍
 */
const removeDayPhotography = (
    { itineraryId, dayNumber }: RemoveDayPhotographyPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/photography/remove`, method: 'POST'
    },
      );
    }
  /**
 * @summary 添加行程跟拍
 */
const addPhotography = (
    { itineraryId, dayNumber }: AddPhotographyPathParameters,
    addPhotographyBody: number,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/photography/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addPhotographyBody
    },
      );
    }
  /**
 * @summary 更新日程餐饮
 */
const updateDayDining = (
    { itineraryId, dayNumber }: UpdateDayDiningPathParameters,
    travelItineraryDining: TravelItineraryDining,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/dining`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItineraryDining
    },
      );
    }
  /**
 * @summary 删除日程餐饮
 */
const removeDayDining = (
    { itineraryId, dayNumber }: RemoveDayDiningPathParameters,
    params: RemoveDayDiningParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/dining/remove`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 删除日程包车
 */
const removeDayCar = (
    { itineraryId, dayNumber }: RemoveDayCarPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/car/remove`, method: 'POST'
    },
      );
    }
  /**
 * @summary 添加行程包车
 */
const addCar = (
    { itineraryId, dayNumber }: AddCarPathParameters,
    addCarBody: number,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/car/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCarBody
    },
      );
    }
  /**
 * @summary 更新日程景点
 */
const updateDayAttractions = (
    { itineraryId, dayNumber }: UpdateDayAttractionsPathParameters,
    updateDayAttractionsBody?: string,
    params?: UpdateDayAttractionsParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/attractions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDayAttractionsBody,
        params
    },
      );
    }
  /**
 * @summary 更新日程景点
 */
const updateDayAttractions1 = (
    { itineraryId, dayNumber }: UpdateDayAttractions1PathParameters,
    updateDayAttractions1Body?: string,
    params?: UpdateDayAttractions1Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/attraction`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDayAttractions1Body,
        params
    },
      );
    }
  /**
 * @summary 更新日程住宿
 */
const updateDayAccommodation = (
    { itineraryId, dayNumber }: UpdateDayAccommodationPathParameters,
    updateDayAccommodationBody: number,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/accommodation`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateDayAccommodationBody
    },
      );
    }
  /**
 * @summary 删除日程住宿
 */
const removeDayAccommodation = (
    { itineraryId, dayNumber }: RemoveDayAccommodationPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayNumber}/accommodation/remove`, method: 'POST'
    },
      );
    }
  /**
 * @summary 删除行程
 */
const remove = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/remove`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 修改行程
 */
const edit12 = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 复制行程
 */
const copy = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/copy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 确认行程
 */
const confirm = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 更新确认状态
 */
const confirmStatus = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/confirmStatus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 一键生成行程
 */
const autoGenerate = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/auto`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 手动创建行程
 */
const add1 = (
    travelItinerary: TravelItinerary,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelItinerary
    },
      );
    }
  /**
 * @summary 查询行程详情
 */
const getInfo3 = (
    { itineraryId }: GetInfo3PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询行程列表
 */
const list13 = (
    params?: List13Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/list`, method: 'GET',
        params
    },
      );
    }
  return {removeDayPhotography,addPhotography,updateDayDining,removeDayDining,removeDayCar,addCar,updateDayAttractions,updateDayAttractions1,updateDayAccommodation,removeDayAccommodation,remove,edit12,copy,confirm,confirmStatus,autoGenerate,add1,getInfo3,list13}};
export type RemoveDayPhotographyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['removeDayPhotography']>>>
export type AddPhotographyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['addPhotography']>>>
export type UpdateDayDiningResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['updateDayDining']>>>
export type RemoveDayDiningResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['removeDayDining']>>>
export type RemoveDayCarResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['removeDayCar']>>>
export type AddCarResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['addCar']>>>
export type UpdateDayAttractionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['updateDayAttractions']>>>
export type UpdateDayAttractions1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['updateDayAttractions1']>>>
export type UpdateDayAccommodationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['updateDayAccommodation']>>>
export type RemoveDayAccommodationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['removeDayAccommodation']>>>
export type RemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['remove']>>>
export type Edit12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['edit12']>>>
export type CopyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['copy']>>>
export type ConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['confirm']>>>
export type ConfirmStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['confirmStatus']>>>
export type AutoGenerateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['autoGenerate']>>>
export type Add1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['add1']>>>
export type GetInfo3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo3']>>>
export type List13Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list13']>>>
