/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddSaveParams,
  AjaxResult,
  EditSaveParams,
  GetInfo4PathParameters,
  ListByBizParams,
  ListParams,
  Remove2Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 删除资源
   */
  const remove2 = (params: Remove2Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/resource/remove`, method: 'POST', params });
  };
  /**
   * @summary 查询资源列表
   */
  const list = (params: ListParams) => {
    return orvalMutator<TableDataInfo>({ url: `/travel18/resource/list`, method: 'POST', params });
  };
  /**
   * @summary 修改资源
   */
  const editSave = (params: EditSaveParams) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/resource/edit`, method: 'POST', params });
  };
  /**
   * @summary 新增资源
   */
  const addSave = (params: AddSaveParams) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/resource/add`, method: 'POST', params });
  };
  /**
   * @summary 获取资源详情
   */
  const getInfo4 = ({ resourceId }: GetInfo4PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/resource/${resourceId}`, method: 'GET' });
  };
  /**
   * @summary 按业务查询资源列表
   */
  const listByBiz = (params: ListByBizParams) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/resource/biz`, method: 'GET', params });
  };
  return { remove2, list, editSave, addSave, getInfo4, listByBiz };
};
export type Remove2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove2']>>>;
export type ListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list']>>>;
export type EditSaveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave']>>>;
export type AddSaveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave']>>>;
export type GetInfo4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo4']>>>;
export type ListByBizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['listByBiz']>>>;
