/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ForceUnlockPathParameters,
  SkipPathParameters,
  UnlockPathParameters,
  UnlockRequest
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 解锁景点
 */
const unlock = (
    { itineraryId, dayId, attractionId }: UnlockPathParameters,
    unlockRequest: UnlockRequest,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayId}/attraction/${attractionId}/unlock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: unlockRequest
    },
      );
    }
  /**
 * @summary 跳过景点
 */
const skip = (
    { itineraryId, dayId, attractionId }: SkipPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayId}/attraction/${attractionId}/skip`, method: 'POST'
    },
      );
    }
  /**
 * @summary 强制解锁景点
 */
const forceUnlock = (
    { itineraryId, dayId, attractionId }: ForceUnlockPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/itinerary/${itineraryId}/day/${dayId}/attraction/${attractionId}/force-unlock`, method: 'POST'
    },
      );
    }
  return {unlock,skip,forceUnlock}};
export type UnlockResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['unlock']>>>
export type SkipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['skip']>>>
export type ForceUnlockResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['forceUnlock']>>>
