/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 生成验证码
   */
  const getCode = () => {
    return orvalMutator<AjaxResult>({ url: `/captchaImage`, method: 'GET' });
  };
  return { getCode };
};
export type GetCodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getCode']>>>;
