/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export14Params,
  List24Params,
  Remove23PathParameters,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysOperlogController = () => {
const export14 = (
    params: Export14Params,
 ) => {
      return orvalMutator<void>(
      {url: `/monitor/operlog/export`, method: 'POST',
        params
    },
      );
    }
  const list24 = (
    params: List24Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/monitor/operlog/list`, method: 'GET',
        params
    },
      );
    }
  const remove23 = (
    { operIds }: Remove23PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/operlog/${operIds}`, method: 'DELETE'
    },
      );
    }
  const clean = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/operlog/clean`, method: 'DELETE'
    },
      );
    }
  return {export14,list24,remove23,clean}};
export type Export14Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysOperlogController>['export14']>>>
export type List24Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysOperlogController>['list24']>>>
export type Remove23Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysOperlogController>['remove23']>>>
export type CleanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysOperlogController>['clean']>>>
