/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo5PathParameters,
  List16Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询打卡点详情（含图片）
 */
const getInfo5 = (
    { checkinId }: GetInfo5PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/checkin/${checkinId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询打卡点列表
 */
const list16 = (
    params?: List16Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/checkin/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo5,list16}};
export type GetInfo5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo5']>>>
export type List16Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list16']>>>
