/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, Login1Params } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 登录方法
   */
  const login1 = (params?: Login1Params) => {
    return orvalMutator<AjaxResult>({ url: `/login`, method: 'POST', params });
  };
  /**
   * @summary 获取路由信息
   */
  const getRouters = () => {
    return orvalMutator<AjaxResult>({ url: `/getRouters`, method: 'GET' });
  };
  /**
   * @summary 获取用户信息
   */
  const getInfo26 = () => {
    return orvalMutator<AjaxResult>({ url: `/getInfo`, method: 'GET' });
  };
  return { login1, getRouters, getInfo26 };
};
export type Login1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['login1']>>>;
export type GetRoutersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['getRouters']>>
>;
export type GetInfo26Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo26']>>>;
