/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo8PathParameters,
  List19Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询住宿详情（含经纬度和图片）
 */
const getInfo8 = (
    { accommodationId }: GetInfo8PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/accommodation/${accommodationId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询住宿列表
 */
const list19 = (
    params?: List19Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/accommodation/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo8,list19}};
export type GetInfo8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo8']>>>
export type List19Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list19']>>>
