/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Edit1Params,
  GetInfo2PathParameters,
  List11Params,
  Remove12PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改游客
   */
  const edit1 = (params?: Edit1Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/tourist`, method: 'PUT', params });
  };
  /**
   * @summary 获取游客详情
   */
  const getInfo2 = ({ touristId }: GetInfo2PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/tourist/${touristId}`, method: 'GET' });
  };
  /**
   * @summary 查询游客列表
   */
  const list11 = (params?: List11Params) => {
    return orvalMutator<TableDataInfo>({ url: `/travel18/tourist/list`, method: 'GET', params });
  };
  /**
   * @summary 删除游客
   */
  const remove12 = ({ touristIds }: Remove12PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/tourist/${touristIds}`, method: 'DELETE' });
  };
  return { edit1, getInfo2, list11, remove12 };
};
export type Edit1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit1']>>>;
export type GetInfo2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo2']>>>;
export type List11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list11']>>>;
export type Remove12Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove12']>>>;
