/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  FeaturedParams,
  List14Params
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 按餐厅ID查询菜品列表
 */
const list14 = (
    params: List14Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/dish/list`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary 首页地道风物：按地区查询各餐厅特色菜（每餐厅≤3，共9）
 */
const featured = (
    params?: FeaturedParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/dish/featured`, method: 'GET',
        params
    },
      );
    }
  return {list14,featured}};
export type List14Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list14']>>>
export type FeaturedResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['featured']>>>
