/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AddParams, AjaxResult, EditParams } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 查询游客喜好
   */
  const getByTouristId = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/preference`, method: 'GET' });
  };
  /**
   * @summary 更新游客喜好
   */
  const edit = (params?: EditParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/preference`, method: 'PUT', params });
  };
  /**
   * @summary 新增游客喜好
   */
  const add = (params?: AddParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/preference`, method: 'POST', params });
  };
  /**
   * @summary 获取游客最近一次喜好配置
   */
  const getLatest = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/preference/latest`, method: 'GET' });
  };
  return { getByTouristId, edit, add, getLatest };
};
export type GetByTouristIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['getByTouristId']>>
>;
export type EditResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit']>>>;
export type AddResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add']>>>;
export type GetLatestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getLatest']>>>;
