/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  Add11Params,
  AjaxResult,
  Edit11Params,
  Export13Params,
  GetConfigKeyPathParameters,
  GetInfo23PathParameters,
  List23Params,
  Remove22PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改参数配置
   */
  const edit11 = (params?: Edit11Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/config`, method: 'PUT', params });
  };
  /**
   * @summary 新增参数配置
   */
  const add11 = (params?: Add11Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/config`, method: 'POST', params });
  };
  /**
   * @summary 导出参数配置
   */
  const export13 = (params?: Export13Params) => {
    return orvalMutator<void>({ url: `/system/config/export`, method: 'POST', params });
  };
  /**
   * @summary 根据参数编号获取详细信息
   */
  const getInfo23 = ({ configId }: GetInfo23PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/config/${configId}`, method: 'GET' });
  };
  /**
   * @summary 获取参数配置列表
   */
  const list23 = (params?: List23Params) => {
    return orvalMutator<TableDataInfo>({ url: `/system/config/list`, method: 'GET', params });
  };
  /**
   * @summary 根据参数键名查询参数值
   */
  const getConfigKey = ({ configKey }: GetConfigKeyPathParameters) => {
    return orvalMutator<AjaxResult>({
      url: `/system/config/configKey/${configKey}`,
      method: 'GET',
    });
  };
  /**
   * @summary 删除参数配置
   */
  const remove22 = ({ configIds }: Remove22PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/config/${configIds}`, method: 'DELETE' });
  };
  /**
   * @summary 刷新参数缓存
   */
  const refreshCache2 = () => {
    return orvalMutator<AjaxResult>({ url: `/system/config/refreshCache`, method: 'DELETE' });
  };
  return { edit11, add11, export13, getInfo23, list23, getConfigKey, remove22, refreshCache2 };
};
export type Edit11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit11']>>>;
export type Add11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add11']>>>;
export type Export13Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export13']>>>;
export type GetInfo23Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo23']>>>;
export type List23Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list23']>>>;
export type GetConfigKeyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['getConfigKey']>>
>;
export type Remove22Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove22']>>>;
export type RefreshCache2Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['refreshCache2']>>
>;
