/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  CityListPathParameters,
  DistrictListPathParameters
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 刷新省市区缓存
 */
const refreshCache = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/region/refresh-cache`, method: 'POST'
    },
      );
    }
  /**
 * @summary 获取树形区域数据
 */
const regionTree = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/region/tree`, method: 'GET'
    },
      );
    }
  /**
 * @summary 获取所有省级数据
 */
const provinceList = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/region/province`, method: 'GET'
    },
      );
    }
  /**
 * @summary 根据城市编码获取区级数据
 */
const districtList = (
    { cityCode }: DistrictListPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/region/district/${cityCode}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 根据省份编码获取市级数据
 */
const cityList = (
    { provinceCode }: CityListPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/region/city/${provinceCode}`, method: 'GET'
    },
      );
    }
  return {refreshCache,regionTree,provinceList,districtList,cityList}};
export type RefreshCacheResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['refreshCache']>>>
export type RegionTreeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['regionTree']>>>
export type ProvinceListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['provinceList']>>>
export type DistrictListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['districtList']>>>
export type CityListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['cityList']>>>
