/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ForecastParams
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询天气预报
 */
const forecast = (
    params: ForecastParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/weather/forecast`, method: 'GET',
        params
    },
      );
    }
  return {forecast}};
export type ForecastResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['forecast']>>>
