/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo6PathParameters,
  List17Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询包车详情（含图片）
 */
const getInfo6 = (
    { carId }: GetInfo6PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/car/${carId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询包车列表
 */
const list17 = (
    params?: List17Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/car/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo6,list17}};
export type GetInfo6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo6']>>>
export type List17Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list17']>>>
