/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AjaxResult, GetInfo4PathParameters, List14Params } from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getC = () => {
  /**
   * @summary 查询包车详情（含图片）
   */
  const getInfo4 = ({ carId }: GetInfo4PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/car/${carId}`, method: 'GET' });
  };
  /**
   * @summary 查询包车列表
   */
  const list14 = (params?: List14Params) => {
    return orvalMutator<AjaxResult>({ url: `/wx/car/list`, method: 'GET', params });
  };
  return { getInfo4, list14 };
};
export type GetInfo4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo4']>>>;
export type List14Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list14']>>>;
