/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetCredentialParams
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getOss = () => {
/**
 * 游客登录后获取STS临时上传凭证，前端拿到凭证后可直接向OSS发起PUT上传。凭证有效期30分钟，仅允许往指定业务目录PUT文件。
 * @summary 获取OSS上传凭证（微信端）
 */
const getCredential = (
    params: GetCredentialParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/oss/credential`, method: 'GET',
        params
    },
      );
    }
  return {getCredential}};
export type GetCredentialResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOss>['getCredential']>>>
