/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ForceLogoutPathParameters,
  List25Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getSysUserOnlineController = () => {
  const list25 = (params: List25Params) => {
    return orvalMutator<TableDataInfo>({ url: `/monitor/online/list`, method: 'GET', params });
  };
  const forceLogout = ({ tokenId }: ForceLogoutPathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/monitor/online/${tokenId}`, method: 'DELETE' });
  };
  return { list25, forceLogout };
};
export type List25Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysUserOnlineController>['list25']>>
>;
export type ForceLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSysUserOnlineController>['forceLogout']>>
>;
