/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ForceLogoutPathParameters,
  List34Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysUserOnlineController = () => {
const list34 = (
    params: List34Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/monitor/online/list`, method: 'GET',
        params
    },
      );
    }
  const forceLogout = (
    { tokenId }: ForceLogoutPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/monitor/online/${tokenId}`, method: 'DELETE'
    },
      );
    }
  return {list34,forceLogout}};
export type List34Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysUserOnlineController>['list34']>>>
export type ForceLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysUserOnlineController>['forceLogout']>>>
