/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  Add8Params,
  AjaxResult,
  Edit8Params,
  Export11Params,
  GetInfo20PathParameters,
  List20Params,
  Remove19PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改字典类型
   */
  const edit8 = (params?: Edit8Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type`, method: 'PUT', params });
  };
  /**
   * @summary 新增字典类型
   */
  const add8 = (params?: Add8Params) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type`, method: 'POST', params });
  };
  /**
   * @summary 导出字典类型
   */
  const export11 = (params?: Export11Params) => {
    return orvalMutator<void>({ url: `/system/dict/type/export`, method: 'POST', params });
  };
  /**
   * @summary 查询字典类型详细
   */
  const getInfo20 = ({ dictId }: GetInfo20PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type/${dictId}`, method: 'GET' });
  };
  /**
   * @summary 获取字典选择框列表
   */
  const optionselect2 = () => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type/optionselect`, method: 'GET' });
  };
  /**
   * @summary 获取字典类型列表
   */
  const list20 = (params?: List20Params) => {
    return orvalMutator<TableDataInfo>({ url: `/system/dict/type/list`, method: 'GET', params });
  };
  /**
   * @summary 删除字典类型
   */
  const remove19 = ({ dictIds }: Remove19PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type/${dictIds}`, method: 'DELETE' });
  };
  /**
   * @summary 刷新字典缓存
   */
  const refreshCache1 = () => {
    return orvalMutator<AjaxResult>({ url: `/system/dict/type/refreshCache`, method: 'DELETE' });
  };
  return { edit8, add8, export11, getInfo20, optionselect2, list20, remove19, refreshCache1 };
};
export type Edit8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit8']>>>;
export type Add8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['add8']>>>;
export type Export11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export11']>>>;
export type GetInfo20Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo20']>>>;
export type Optionselect2Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['optionselect2']>>
>;
export type List20Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list20']>>>;
export type Remove19Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove19']>>>;
export type RefreshCache1Result = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['refreshCache1']>>
>;
