/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  CityListPathParameters,
  DistrictListPathParameters,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 查询省级列表
   */
  const provinceList = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/region/province`, method: 'GET' });
  };
  /**
   * @summary 根据市编码查询区级列表
   */
  const districtList = ({ cityCode }: DistrictListPathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/region/district/${cityCode}`, method: 'GET' });
  };
  /**
   * @summary 根据省编码查询市级列表
   */
  const cityList = ({ provinceCode }: CityListPathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/wx/region/city/${provinceCode}`, method: 'GET' });
  };
  return { provinceList, districtList, cityList };
};
export type ProvinceListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['provinceList']>>
>;
export type DistrictListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['districtList']>>
>;
export type CityListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['cityList']>>>;
