/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export10Params,
  GetInfo17PathParameters,
  List17Params,
  Remove16PathParameters,
  SysPost,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysPostController = () => {
const edit5 = (
    sysPost: SysPost,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/post`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sysPost
    },
      );
    }
  const add5 = (
    sysPost: SysPost,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/post`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sysPost
    },
      );
    }
  const export10 = (
    params: Export10Params,
 ) => {
      return orvalMutator<void>(
      {url: `/system/post/export`, method: 'POST',
        params
    },
      );
    }
  const getInfo17 = (
    { postId }: GetInfo17PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/post/${postId}`, method: 'GET'
    },
      );
    }
  const optionselect1 = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/post/optionselect`, method: 'GET'
    },
      );
    }
  const list17 = (
    params: List17Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/system/post/list`, method: 'GET',
        params
    },
      );
    }
  const remove16 = (
    { postIds }: Remove16PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/post/${postIds}`, method: 'DELETE'
    },
      );
    }
  return {edit5,add5,export10,getInfo17,optionselect1,list17,remove16}};
export type Edit5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['edit5']>>>
export type Add5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['add5']>>>
export type Export10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['export10']>>>
export type GetInfo17Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['getInfo17']>>>
export type Optionselect1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['optionselect1']>>>
export type List17Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['list17']>>>
export type Remove16Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysPostController>['remove16']>>>
