/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export3Params,
  GetDishesByDiningPathParameters,
  GetInfo8PathParameters,
  List4Params,
  Remove6Params,
  TableDataInfo,
  TravelDining
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 删除餐饮
 */
const remove6 = (
    params: Remove6Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dining/remove`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 查询餐饮列表
 */
const list4 = (
    params: List4Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/dining/list`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 导出餐饮列表
 */
const export3 = (
    params: Export3Params,
 ) => {
      return orvalMutator<void>(
      {url: `/travel18/dining/export`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 修改保存餐饮
 */
const editSave4 = (
    travelDining: TravelDining,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dining/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelDining
    },
      );
    }
  /**
 * @summary 新增保存餐饮
 */
const addSave5 = (
    travelDining: TravelDining,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dining/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelDining
    },
      );
    }
  /**
 * @summary 获取餐饮详情
 */
const getInfo8 = (
    { diningId }: GetInfo8PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dining/${diningId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询餐饮下的菜品
 */
const getDishesByDining = (
    { diningId }: GetDishesByDiningPathParameters,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/dining/${diningId}/dishes`, method: 'GET'
    },
      );
    }
  return {remove6,list4,export3,editSave4,addSave5,getInfo8,getDishesByDining}};
export type Remove6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove6']>>>
export type List4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list4']>>>
export type Export3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export3']>>>
export type EditSave4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave4']>>>
export type AddSave5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave5']>>>
export type GetInfo8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo8']>>>
export type GetDishesByDiningResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getDishesByDining']>>>
