/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetCredential1Params
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getOss = () => {
/**
 * 通过STS AssumeRole生成临时上传凭证，前端拿到凭证后可直接向OSS发起PUT上传，不经过后端转发。凭证有效期30分钟，仅允许往指定业务目录PUT文件。
 * @summary 获取OSS上传凭证（管理端）
 */
const getCredential1 = (
    params: GetCredential1Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/oss/credential`, method: 'GET',
        params
    },
      );
    }
  return {getCredential1}};
export type GetCredential1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getOss>['getCredential1']>>>
