/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  Export4Params
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 导出打卡点列表
 */
const export4 = (
    params: Export4Params,
 ) => {
      return orvalMutator<void>(
      {url: `/travel18/checkin/export`, method: 'POST',
        params
    },
      );
    }
  return {export4}};
export type Export4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export4']>>>
