/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddSave8Params,
  AjaxResult,
  EditSave8Params,
  Export7Params,
  GetInfo13PathParameters,
  List8Params,
  Remove11Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 删除住宿
   */
  const remove11 = (params: Remove11Params) => {
    return orvalMutator<AjaxResult>({
      url: `/travel18/accommodation/remove`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 查询住宿列表
   */
  const list8 = (params: List8Params) => {
    return orvalMutator<TableDataInfo>({
      url: `/travel18/accommodation/list`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 导出住宿列表
   */
  const export7 = (params: Export7Params) => {
    return orvalMutator<void>({ url: `/travel18/accommodation/export`, method: 'POST', params });
  };
  /**
   * @summary 修改保存住宿
   */
  const editSave8 = (params: EditSave8Params) => {
    return orvalMutator<AjaxResult>({
      url: `/travel18/accommodation/edit`,
      method: 'POST',
      params,
    });
  };
  /**
   * @summary 新增保存住宿
   */
  const addSave8 = (params: AddSave8Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/accommodation/add`, method: 'POST', params });
  };
  /**
   * @summary 获取住宿详情
   */
  const getInfo13 = ({ accommodationId }: GetInfo13PathParameters) => {
    return orvalMutator<AjaxResult>({
      url: `/travel18/accommodation/${accommodationId}`,
      method: 'GET',
    });
  };
  return { remove11, list8, export7, editSave8, addSave8, getInfo13 };
};
export type Remove11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove11']>>>;
export type List8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list8']>>>;
export type Export7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export7']>>>;
export type EditSave8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave8']>>>;
export type AddSave8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave8']>>>;
export type GetInfo13Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo13']>>>;
