/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo4PathParameters,
  List15Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询餐饮详情（含图片）
 */
const getInfo4 = (
    { diningId }: GetInfo4PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/dining/${diningId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询餐饮列表
 */
const list15 = (
    params?: List15Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/dining/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo4,list15}};
export type GetInfo4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo4']>>>
export type List15Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list15']>>>
