/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ExcludeChildPathParameters,
  GetInfo22PathParameters,
  List22Params,
  Remove21PathParameters,
  SysDept,
  UpdateSort1Body
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getSysDeptController = () => {
const edit10 = (
    sysDept: SysDept,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sysDept
    },
      );
    }
  const add10 = (
    sysDept: SysDept,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sysDept
    },
      );
    }
  const updateSort1 = (
    updateSort1Body: UpdateSort1Body,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept/updateSort`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSort1Body
    },
      );
    }
  const getInfo22 = (
    { deptId }: GetInfo22PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept/${deptId}`, method: 'GET'
    },
      );
    }
  const remove21 = (
    { deptId }: Remove21PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept/${deptId}`, method: 'DELETE'
    },
      );
    }
  const list22 = (
    params: List22Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept/list`, method: 'GET',
        params
    },
      );
    }
  const excludeChild = (
    { deptId }: ExcludeChildPathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/system/dept/list/exclude/${deptId}`, method: 'GET'
    },
      );
    }
  return {edit10,add10,updateSort1,getInfo22,remove21,list22,excludeChild}};
export type Edit10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['edit10']>>>
export type Add10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['add10']>>>
export type UpdateSort1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['updateSort1']>>>
export type GetInfo22Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['getInfo22']>>>
export type Remove21Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['remove21']>>>
export type List22Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['list22']>>>
export type ExcludeChildResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSysDeptController>['excludeChild']>>>
