/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Export2Params,
  GetInfo7PathParameters,
  List3Params,
  Remove5Params,
  TableDataInfo,
  TravelDish
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 删除菜品
 */
const remove5 = (
    params: Remove5Params,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dish/remove`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 查询菜品列表
 */
const list3 = (
    params: List3Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/travel18/dish/list`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 导出菜品列表
 */
const export2 = (
    params: Export2Params,
 ) => {
      return orvalMutator<void>(
      {url: `/travel18/dish/export`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary 修改保存菜品
 */
const editSave3 = (
    travelDish: TravelDish,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dish/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelDish
    },
      );
    }
  /**
 * @summary 新增保存菜品
 */
const addSave4 = (
    travelDish: TravelDish,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dish/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelDish
    },
      );
    }
  /**
 * @summary 获取菜品详情
 */
const getInfo7 = (
    { dishId }: GetInfo7PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/travel18/dish/${dishId}`, method: 'GET'
    },
      );
    }
  return {remove5,list3,export2,editSave3,addSave4,getInfo7}};
export type Remove5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove5']>>>
export type List3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list3']>>>
export type Export2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export2']>>>
export type EditSave3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave3']>>>
export type AddSave4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave4']>>>
export type GetInfo7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo7']>>>
