/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type Add2Params = {
  configId?: number;
  regionCode?: string;
  regionName?: string;
  regionLevel?: string;
  version?: number;
  status?: string;
  delFlag?: string;
  staminaLimit0?: number;
  staminaLimit1?: number;
  staminaLimit2?: number;
  staminaLimit3?: number;
  recoveryStartDay?: number;
  recoveryThreshold?: number;
  recoveryLimit2635?: number;
  recoveryLimit3650?: number;
  recoveryLimit51Plus?: number;
  singleAttractionThreshold?: number;
  staminaFormulaCoefficient?: number;
  periodLimitMorning?: number;
  periodLimitAfternoon?: number;
  periodLimitEvening?: number;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
