/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { AddFoodLikesListItem } from './addFoodLikesListItem';
import type { AddHealthTagsListItem } from './addHealthTagsListItem';
import type { AddStayPrefListItem } from './addStayPrefListItem';
import type { AddTravelLikesListItem } from './addTravelLikesListItem';

export type AddParams = {
  preferenceId?: number;
  touristId?: number;
  tripId?: number;
  gender?: string;
  birthYear?: number;
  stamina?: string;
  travelLikes?: string;
  foodLikes?: string;
  stayPref?: string;
  healthTags?: string;
  status?: string;
  delFlag?: string;
  staminaLabel?: string;
  travelLikesList?: AddTravelLikesListItem[];
  foodLikesList?: AddFoodLikesListItem[];
  stayPrefList?: AddStayPrefListItem[];
  healthTagsList?: AddHealthTagsListItem[];
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
