/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type AddSave3Params = {
  dishId?: number;
  diningId?: number;
  dishName: string;
  dishDesc?: string;
  specialStar?: number;
  darkLevel?: string;
  price?: number;
  seasonal?: string;
  reservation?: string;
  status?: string;
  delFlag?: string;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
