/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type AddSave4Params = {
  diningId?: number;
  diningName: string;
  diningDesc?: string;
  diningTips?: string;
  province?: string;
  city?: string;
  district?: string;
  address?: string;
  longitude?: number;
  latitude?: number;
  petFriendly?: string;
  diningNature?: string;
  avgCost?: number;
  recommendRating?: number;
  parkingAvailable?: string;
  status?: string;
  delFlag?: string;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
