/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysDept } from './sysDept';
import type { SysRole } from './sysRole';

export type AllocatedListParams = {
  userId?: number;
  deptId?: number;
  userName?: string;
  nickName?: string;
  email?: string;
  phonenumber?: string;
  sex?: string;
  avatar?: string;
  password?: string;
  status?: string;
  delFlag?: string;
  loginIp?: string;
  loginDate?: Date;
  pwdUpdateDate?: Date;
  'dept.deptId'?: number;
  'dept.parentId'?: number;
  'dept.ancestors'?: string;
  'dept.deptName'?: string;
  'dept.orderNum'?: number;
  'dept.leader'?: string;
  'dept.phone'?: string;
  'dept.email'?: string;
  'dept.status'?: string;
  'dept.delFlag'?: string;
  'dept.parentName'?: string;
  'dept.children'?: SysDept[];
  'dept.createBy'?: string;
  'dept.createTime'?: Date;
  'dept.updateBy'?: string;
  'dept.updateTime'?: Date;
  'dept.remark'?: string;
  roles?: SysRole[];
  roleIds?: number[];
  postIds?: number[];
  roleId?: number;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
