/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type EditSave2Params = {
  lineId?: number;
  lineName: string;
  province?: string;
  city?: string;
  district?: string;
  status?: string;
  delFlag?: string;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
