/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { Edit2FoodLikesListItem } from './edit2FoodLikesListItem';
import type { Edit2HealthTagsListItem } from './edit2HealthTagsListItem';
import type { Edit2StayPrefListItem } from './edit2StayPrefListItem';
import type { Edit2TravelLikesListItem } from './edit2TravelLikesListItem';

export type Edit2Params = {
  preferenceId?: number;
  touristId?: number;
  tripId?: number;
  gender?: string;
  birthYear?: number;
  stamina?: string;
  travelLikes?: string;
  foodLikes?: string;
  stayPref?: string;
  healthTags?: string;
  status?: string;
  delFlag?: string;
  staminaLabel?: string;
  travelLikesList?: Edit2TravelLikesListItem[];
  foodLikesList?: Edit2FoodLikesListItem[];
  stayPrefList?: Edit2StayPrefListItem[];
  healthTagsList?: Edit2HealthTagsListItem[];
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
