/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelLine } from './travelLine';

export type Export6Params = {
  attractionId?: number;
  lineIds?: number[];
  lines?: TravelLine[];
  attractionName: string;
  attractionShortName?: string;
  attractionDescription?: string;
  attractionBlurb?: string;
  province?: string;
  city?: string;
  district?: string;
  longitude?: number;
  latitude?: number;
  attractionNotes?: string;
  blindStatus?: string;
  classicRating?: string;
  leisureRating?: string;
  visitDuration?: string;
  openTime?: string;
  familyFriendly?: string;
  ticketPriceA?: number;
  ticketPriceC?: number;
  reservationRequired?: string;
  perCost?: string;
  indoorOutdoor?: string;
  closedDay?: string;
  specialPeriod?: string;
  badFactors?: string;
  attractionType?: string;
  status?: string;
  delFlag?: string;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
