/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type ListByBizParams = {
/**
 * 业务类型：attraction/checkin/accommodation/dining/car/photography
 */
bizType: string;
/**
 * 业务实体ID
 */
bizId: number;
};
