/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type List11Params = {
  touristId?: number;
  openid?: string;
  unionid?: string;
  sessionKey?: string;
  nickname?: string;
  avatarUrl?: string;
  gender?: string;
  phone?: string;
  realName?: string;
  idCard?: string;
  status?: string;
  delFlag?: string;
  loginIp?: string;
  loginDate?: Date;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
