/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelTemplateDay } from './travelTemplateDay';

export type List12Params = {
  templateId?: number;
  templateName?: string;
  templateDesc?: string;
  province?: string;
  city?: string;
  district?: string;
  baseDays?: number;
  minDays?: number;
  maxDays?: number;
  staminaLevel?: string;
  travelTags?: string;
  includePhotography?: string;
  includeCar?: string;
  version?: number;
  status?: string;
  delFlag?: string;
  days?: TravelTemplateDay[];
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
