/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { List13FoodLikesListItem } from './list13FoodLikesListItem';
import type { List13HealthTagsListItem } from './list13HealthTagsListItem';
import type { List13StayPrefListItem } from './list13StayPrefListItem';
import type { List13TravelLikesListItem } from './list13TravelLikesListItem';

export type List13Params = {
  preferenceId?: number;
  touristId?: number;
  tripId?: number;
  gender?: string;
  birthYear?: number;
  stamina?: string;
  travelLikes?: string;
  foodLikes?: string;
  stayPref?: string;
  healthTags?: string;
  status?: string;
  delFlag?: string;
  staminaLabel?: string;
  travelLikesList?: List13TravelLikesListItem[];
  foodLikesList?: List13FoodLikesListItem[];
  stayPrefList?: List13StayPrefListItem[];
  healthTagsList?: List13HealthTagsListItem[];
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
};
