/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

/**
 * 用户登录对象
 */
export interface LoginBody {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 验证码 */
  code?: string;
  /** 验证码唯一标识 */
  uuid?: string;
}
