/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelItineraryDay } from './travelItineraryDay';

export type RemoveParams = {
  itineraryId?: number;
  touristId?: number;
  templateId?: number;
  templateDayIds?: string;
  itineraryName?: string;
  province?: string;
  city?: string;
  district?: string;
  startDate?: Date;
  days?: number;
  status?: string;
  createFrom?: string;
  version?: number;
  totalCost?: number;
  remark?: string;
  delFlag?: string;
  daysList?: TravelItineraryDay[];
  statusLabel?: string;
  createFromLabel?: string;
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
};
