/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysConfigParams } from './sysConfigParams';

export interface SysConfig {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysConfigParams;
  configId?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  configName: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  configKey: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  configValue: string;
  configType?: string;
}
