/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysDictTypeParams } from './sysDictTypeParams';

export interface SysDictType {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysDictTypeParams;
  dictId?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  dictName: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @pattern ^[a-z][a-z0-9_]*$
   */
  dictType: string;
  status?: string;
}
