/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysDictDataParams } from './sysDictDataParams';

export interface SysDictData {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysDictDataParams;
  dictCode?: number;
  dictSort?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  dictLabel: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  dictValue: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  dictType: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  cssClass?: string;
  listClass?: string;
  isDefault?: string;
  status?: string;
  default?: boolean;
}
