/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysDeptParams } from './sysDeptParams';

export interface SysDept {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysDeptParams;
  deptId?: number;
  parentId?: number;
  ancestors?: string;
  /**
   * @minLength 0
   * @maxLength 30
   */
  deptName: string;
  orderNum: number;
  leader?: string;
  /**
   * @minLength 0
   * @maxLength 11
   */
  phone?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  email?: string;
  status?: string;
  delFlag?: string;
  parentName?: string;
  children?: SysDept[];
}
