/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysMenuParams } from './sysMenuParams';

export interface SysMenu {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysMenuParams;
  menuId?: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  menuName: string;
  parentName?: string;
  parentId?: number;
  orderNum: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  path?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  component?: string;
  query?: string;
  routeName?: string;
  isFrame?: string;
  isCache?: string;
  menuType: string;
  visible?: string;
  status?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  perms?: string;
  icon?: string;
  children?: SysMenu[];
}
