/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysNoticeParams } from './sysNoticeParams';

export interface SysNotice {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysNoticeParams;
  noticeId?: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  noticeTitle: string;
  noticeType?: string;
  noticeContent?: string;
  status?: string;
  isRead?: boolean;
}
