/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysPostParams } from './sysPostParams';

export interface SysPost {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysPostParams;
  postId?: number;
  /**
   * @minLength 0
   * @maxLength 64
   */
  postCode: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  postName: string;
  postSort: number;
  status?: string;
  flag?: boolean;
}
