/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysRoleParams } from './sysRoleParams';

export interface SysRole {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysRoleParams;
  roleId?: number;
  /**
   * @minLength 0
   * @maxLength 30
   */
  roleName: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  roleKey: string;
  roleSort: number;
  dataScope?: string;
  menuCheckStrictly?: boolean;
  deptCheckStrictly?: boolean;
  status?: string;
  delFlag?: string;
  flag?: boolean;
  menuIds?: number[];
  deptIds?: number[];
  permissions?: string[];
  admin?: boolean;
}
