/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { SysUserParams } from './sysUserParams';
import type { SysDept } from './sysDept';
import type { SysRole } from './sysRole';

export interface SysUser {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: SysUserParams;
  userId?: number;
  deptId?: number;
  /**
   * @minLength 0
   * @maxLength 30
   */
  userName: string;
  /**
   * @minLength 0
   * @maxLength 30
   */
  nickName?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 11
   */
  phonenumber?: string;
  sex?: string;
  avatar?: string;
  password?: string;
  status?: string;
  delFlag?: string;
  loginIp?: string;
  loginDate?: Date;
  pwdUpdateDate?: Date;
  dept?: SysDept;
  roles?: SysRole[];
  roleIds?: number[];
  postIds?: number[];
  roleId?: number;
  admin?: boolean;
}
