/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelLocalSpecialtyDishAttachmentsItem } from './travelLocalSpecialtyDishAttachmentsItem';
import type { TravelLocalSpecialtyDishParams } from './travelLocalSpecialtyDishParams';

export interface TravelLocalSpecialtyDish {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelLocalSpecialtyDishParams;
  specialtyId?: number;
  specialtyName: string;
  specialtyDesc?: string;
  province?: string;
  city?: string;
  district?: string;
  specialStar?: number;
  darkLevel?: string;
  price?: number;
  seasonal?: string;
  reservation?: string;
  status?: string;
  delFlag?: string;
  attachments?: TravelLocalSpecialtyDishAttachmentsItem[];
}
