/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelAccommodation } from './travelAccommodation';
import type { TravelAttraction } from './travelAttraction';
import type { TravelCar } from './travelCar';
import type { TravelDining } from './travelDining';
import type { TravelItineraryDayParams } from './travelItineraryDayParams';
import type { TravelPhotography } from './travelPhotography';

export type TravelItineraryDay = {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelItineraryDayParams;
  itineraryDayId?: number;
  itineraryId?: number;
  templateDayId?: number;
  dayNumber?: number;
  dayTheme?: string;
  attractionIds?: string;
  attractionCriteria?: string;
  touristAttractionIds?: string;
  accommodationId?: number;
  touristAccommodationId?: number;
  breakfastId?: number;
  touristBreakfastId?: number;
  lunchId?: number;
  touristLunchId?: number;
  dinnerId?: number;
  touristDinnerId?: number;
  photographyId?: number;
  touristPhotographyId?: number;
  carId?: number;
  touristCarId?: number;
  accommodation?: TravelAccommodation;
  touristAccommodation?: TravelAccommodation;
  attractionList?: TravelAttraction[];
  touristAttractionList?: TravelAttraction[];
  breakfast?: TravelDining;
  touristBreakfast?: TravelDining;
  lunch?: TravelDining;
  touristLunch?: TravelDining;
  dinner?: TravelDining;
  touristDinner?: TravelDining;
  photography?: TravelPhotography;
  touristPhotography?: TravelPhotography;
  car?: TravelCar;
  touristCar?: TravelCar;
  delFlag?: string;
};
