/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelItineraryAttachmentsItem } from './travelItineraryAttachmentsItem';
import type { TravelItineraryDay } from './travelItineraryDay';
import type { TravelItineraryParams } from './travelItineraryParams';

export type TravelItinerary = {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelItineraryParams;
  itineraryId?: number;
  touristId?: number;
  templateId?: number;
  templateDayIds?: string;
  itineraryName?: string;
  province?: string;
  city?: string;
  district?: string;
  startDate?: Date;
  days?: number;
  status?: string;
  createFrom?: string;
  version?: number;
  totalCost?: number;
  delFlag?: string;
  daysList?: TravelItineraryDay[];
  statusLabel?: string;
  createFromLabel?: string;
  attachments?: TravelItineraryAttachmentsItem[];
};
