/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelLineParams } from './travelLineParams';
import type { TravelLineAttachmentsItem } from './travelLineAttachmentsItem';

export interface TravelLine {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelLineParams;
  lineId?: number;
  lineName: string;
  province?: string;
  city?: string;
  district?: string;
  status?: string;
  delFlag?: string;
  attachments?: TravelLineAttachmentsItem[];
}
