/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelTemplateAttachmentsItem } from './travelTemplateAttachmentsItem';
import type { TravelTemplateDay } from './travelTemplateDay';
import type { TravelTemplateParams } from './travelTemplateParams';

export type TravelTemplate = {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelTemplateParams;
  templateId?: number;
  templateName?: string;
  templateDesc?: string;
  province?: string;
  city?: string;
  district?: string;
  baseDays?: number;
  minDays?: number;
  maxDays?: number;
  staminaLevel?: string;
  travelTags?: string;
  includePhotography?: string;
  includeCar?: string;
  version?: number;
  status?: string;
  delFlag?: string;
  days?: TravelTemplateDay[];
  attachments?: TravelTemplateAttachmentsItem[];
};
