/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelAccommodationParams } from './travelAccommodationParams';
import type { TravelAccommodationAttachmentsItem } from './travelAccommodationAttachmentsItem';

export interface TravelAccommodation {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelAccommodationParams;
  accommodationId?: number;
  accommodationName: string;
  accommodationDesc?: string;
  contactPhone?: string;
  province?: string;
  city?: string;
  district?: string;
  address?: string;
  longitude?: number;
  latitude?: number;
  accommodationType?: string;
  breakfastIncluded?: string;
  petFriendly?: string;
  priceMin?: number;
  priceMax?: number;
  status?: string;
  delFlag?: string;
  attachments?: TravelAccommodationAttachmentsItem[];
}
