/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelAlgorithmConfigHistoryParams } from './travelAlgorithmConfigHistoryParams';

export interface TravelAlgorithmConfigHistory {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelAlgorithmConfigHistoryParams;
  historyId?: number;
  configId?: number;
  regionCode?: string;
  regionName?: string;
  version?: number;
  operation?: string;
  oldConfigSnapshot?: string;
  newConfigSnapshot?: string;
  operateTime?: Date;
  operateBy?: string;
}
