/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelCarParams } from './travelCarParams';

export interface TravelCar {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelCarParams;
  carId?: number;
  nickname: string;
  gender?: string;
  introduction?: string;
  contactInfo?: string;
  price?: number;
  carModel?: string;
  seatCount?: number;
  drivingYears?: number;
  status?: string;
  delFlag?: string;
  attachments?: string;
}
