/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelTouristPreferenceParams } from './travelTouristPreferenceParams';
import type { TravelTouristPreferenceTravelLikesListItem } from './travelTouristPreferenceTravelLikesListItem';
import type { TravelTouristPreferenceFoodLikesListItem } from './travelTouristPreferenceFoodLikesListItem';
import type { TravelTouristPreferenceStayPrefListItem } from './travelTouristPreferenceStayPrefListItem';
import type { TravelTouristPreferenceHealthTagsListItem } from './travelTouristPreferenceHealthTagsListItem';

export interface TravelTouristPreference {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelTouristPreferenceParams;
  preferenceId?: number;
  touristId?: number;
  tripId?: number;
  gender?: string;
  birthYear?: number;
  stamina?: string;
  travelLikes?: string;
  foodLikes?: string;
  stayPref?: string;
  healthTags?: string;
  status?: string;
  delFlag?: string;
  staminaLabel?: string;
  travelLikesList?: TravelTouristPreferenceTravelLikesListItem[];
  foodLikesList?: TravelTouristPreferenceFoodLikesListItem[];
  stayPrefList?: TravelTouristPreferenceStayPrefListItem[];
  healthTagsList?: TravelTouristPreferenceHealthTagsListItem[];
}
