/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelResourceParams } from './travelResourceParams';

export interface TravelResource {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelResourceParams;
  resourceId?: number;
  /**
   * @minLength 0
   * @maxLength 30
   */
  bizType: string;
  bizId: number;
  resourceType: string;
  resourcePurpose?: string;
  fileName?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  fileUrl: string;
  fileSize?: number;
  mimeType?: string;
  fileExt?: string;
  sortOrder?: number;
  status?: string;
  delFlag?: string;
}
