/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelDishParams } from './travelDishParams';

export interface TravelDish {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelDishParams;
  dishId?: number;
  diningId?: number;
  dishName: string;
  dishDesc?: string;
  specialStar?: number;
  darkLevel?: string;
  price?: number;
  seasonal?: string;
  reservation?: string;
  status?: string;
  delFlag?: string;
  attachments?: string;
}
