/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelPhotographyParams } from './travelPhotographyParams';

export interface TravelPhotography {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelPhotographyParams;
  photographyId?: number;
  nickname: string;
  gender?: string;
  introduction?: string;
  contactInfo?: string;
  price?: number;
  recommendRating?: number;
  equipment?: string;
  status?: string;
  delFlag?: string;
  attachments?: string;
}
