/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type { TravelTemplateDayParams } from './travelTemplateDayParams';

export interface TravelTemplateDay {
  createBy?: string;
  createTime?: Date;
  updateBy?: string;
  updateTime?: Date;
  remark?: string;
  params?: TravelTemplateDayParams;
  templateDayId?: number;
  templateId?: number;
  dayNumber?: number;
  dayTheme?: string;
  attractionIds?: string;
  attractionCriteria?: string;
  leisureMin?: number;
  leisureMax?: number;
  accommodationId?: number;
  breakfastDiningId?: number;
  lunchDiningId?: number;
  dinnerDiningId?: number;
  photographyId?: number;
  carId?: number;
  status?: string;
  delFlag?: string;
}
