/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */

export type UpdateParams = {
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 用户名称
   */
  username?: string;
  /**
   * 用户密码
   */
  password?: string;
  /**
   * 用户手机
   */
  mobile?: string;
};
