/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  GetInfo1PathParameters,
  List11Params,
  TableDataInfo
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const getC = () => {
/**
 * @summary 查询跟拍详情（含图片）
 */
const getInfo1 = (
    { photographyId }: GetInfo1PathParameters,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/photography/${photographyId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary 查询跟拍列表
 */
const list11 = (
    params?: List11Params,
 ) => {
      return orvalMutator<TableDataInfo>(
      {url: `/wx/photography/list`, method: 'GET',
        params
    },
      );
    }
  return {getInfo1,list11}};
export type GetInfo1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['getInfo1']>>>
export type List11Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getC>['list11']>>>
