/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  Edit2Params,
  GetInfo5PathParameters,
  List13Params,
  Remove13PathParameters,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 修改游客喜好
   */
  const edit2 = (params?: Edit2Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/preference`, method: 'PUT', params });
  };
  /**
   * @summary 获取游客喜好详情
   */
  const getInfo5 = ({ preferenceId }: GetInfo5PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/preference/${preferenceId}`, method: 'GET' });
  };
  /**
   * @summary 查询游客喜好列表
   */
  const list13 = (params?: List13Params) => {
    return orvalMutator<TableDataInfo>({ url: `/travel18/preference/list`, method: 'GET', params });
  };
  /**
   * @summary 删除游客喜好
   */
  const remove13 = ({ preferenceIds }: Remove13PathParameters) => {
    return orvalMutator<AjaxResult>({
      url: `/travel18/preference/${preferenceIds}`,
      method: 'DELETE',
    });
  };
  return { edit2, getInfo5, list13, remove13 };
};
export type Edit2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['edit2']>>>;
export type GetInfo5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo5']>>>;
export type List13Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list13']>>>;
export type Remove13Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove13']>>>;
