/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  BindPhoneBody,
  LoginBody,
  TestTokenBody,
  UpdateProfileParams,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 更新游客资料
   */
  const updateProfile = (params?: UpdateProfileParams) => {
    return orvalMutator<AjaxResult>({ url: `/wx/auth/updateProfile`, method: 'PUT', params });
  };
  /**
   * @summary 测试用-直接获取token（上线前删除）
   */
  const testToken = (testTokenBody: TestTokenBody) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/auth/testToken`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: testTokenBody,
    });
  };
  /**
   * @summary 微信登录
   */
  const login = (loginBody: LoginBody) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginBody,
    });
  };
  /**
   * @summary 绑定手机号
   */
  const bindPhone = (bindPhoneBody: BindPhoneBody) => {
    return orvalMutator<AjaxResult>({
      url: `/wx/auth/bindPhone`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: bindPhoneBody,
    });
  };
  /**
   * @summary 获取游客信息
   */
  const getUserInfo = () => {
    return orvalMutator<AjaxResult>({ url: `/wx/auth/getUserInfo`, method: 'GET' });
  };
  return { updateProfile, testToken, login, bindPhone, getUserInfo };
};
export type UpdateProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['updateProfile']>>
>;
export type TestTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['testToken']>>>;
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['login']>>>;
export type BindPhoneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['bindPhone']>>>;
export type GetUserInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>['getUserInfo']>>
>;
