/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  BindPhoneBody,
  TestTokenBody,
  TravelTourist,
  WxLoginBody
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * @summary 更新游客资料
 */
const updateProfile = (
    travelTourist: TravelTourist,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/auth/updateProfile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: travelTourist
    },
      );
    }
  /**
 * @summary 测试用-直接获取token（上线前删除）
 */
const testToken = (
    testTokenBody: TestTokenBody,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/auth/testToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: testTokenBody
    },
      );
    }
  /**
 * @summary 微信登录
 */
const wxLogin = (
    wxLoginBody: WxLoginBody,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wxLoginBody
    },
      );
    }
  /**
 * @summary 绑定手机号
 */
const bindPhone = (
    bindPhoneBody: BindPhoneBody,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/auth/bindPhone`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bindPhoneBody
    },
      );
    }
  /**
 * @summary 获取游客信息
 */
const getUserInfo = (
    
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/auth/getUserInfo`, method: 'GET'
    },
      );
    }
  return {updateProfile,testToken,wxLogin,bindPhone,getUserInfo}};
export type UpdateProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['updateProfile']>>>
export type TestTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['testToken']>>>
export type WxLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['wxLogin']>>>
export type BindPhoneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['bindPhone']>>>
export type GetUserInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getUserInfo']>>>
