/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddSave2Params,
  AjaxResult,
  EditSave2Params,
  Export1Params,
  List2Params,
  Remove4Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 删除线路
   */
  const remove4 = (params: Remove4Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/line/remove`, method: 'POST', params });
  };
  /**
   * @summary 查询线路列表
   */
  const list2 = (params: List2Params) => {
    return orvalMutator<TableDataInfo>({ url: `/travel18/line/list`, method: 'POST', params });
  };
  /**
   * @summary 导出线路列表
   */
  const export1 = (params: Export1Params) => {
    return orvalMutator<void>({ url: `/travel18/line/export`, method: 'POST', params });
  };
  /**
   * @summary 修改保存线路
   */
  const editSave2 = (params: EditSave2Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/line/edit`, method: 'POST', params });
  };
  /**
   * @summary 新增保存线路
   */
  const addSave2 = (params: AddSave2Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/line/add`, method: 'POST', params });
  };
  return { remove4, list2, export1, editSave2, addSave2 };
};
export type Remove4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove4']>>>;
export type List2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list2']>>>;
export type Export1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export1']>>>;
export type EditSave2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave2']>>>;
export type AddSave2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave2']>>>;
