/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AddSave6Params,
  AjaxResult,
  EditSave6Params,
  Export5Params,
  GetInfo10PathParameters,
  List6Params,
  Remove8Params,
  TableDataInfo,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const get = () => {
  /**
   * @summary 删除包车
   */
  const remove8 = (params: Remove8Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/car/remove`, method: 'POST', params });
  };
  /**
   * @summary 查询包车列表
   */
  const list6 = (params: List6Params) => {
    return orvalMutator<TableDataInfo>({ url: `/travel18/car/list`, method: 'POST', params });
  };
  /**
   * @summary 导出包车列表
   */
  const export5 = (params: Export5Params) => {
    return orvalMutator<void>({ url: `/travel18/car/export`, method: 'POST', params });
  };
  /**
   * @summary 修改保存包车
   */
  const editSave6 = (params: EditSave6Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/car/edit`, method: 'POST', params });
  };
  /**
   * @summary 新增保存包车
   */
  const addSave6 = (params: AddSave6Params) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/car/add`, method: 'POST', params });
  };
  /**
   * @summary 获取包车详情
   */
  const getInfo10 = ({ carId }: GetInfo10PathParameters) => {
    return orvalMutator<AjaxResult>({ url: `/travel18/car/${carId}`, method: 'GET' });
  };
  return { remove8, list6, export5, editSave6, addSave6, getInfo10 };
};
export type Remove8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['remove8']>>>;
export type List6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['list6']>>>;
export type Export5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['export5']>>>;
export type EditSave6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['editSave6']>>>;
export type AddSave6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave6']>>>;
export type GetInfo10Result = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['getInfo10']>>>;
