/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 十八线_接口文档
 * 十八线——小众旅游
 * OpenAPI spec version: 版本号:0.0.1
 */
import type {
  AjaxResult,
  ListByBizParams,
  TravelResource
} from '../../../types/api';

import { orvalMutator } from '../../../utils/orval-mutator';



  export const get = () => {
/**
 * 游客前端直传OSS成功后，调用此接口保存资源元数据（objectKey、文件名、大小、类型等）。需游客登录态。
 * @summary 微信端新增资源
 */
const addSave = (
    travelResource: TravelResource,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/resource/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: travelResource
    },
      );
    }
  /**
 * 按业务类型和业务实体ID查询关联的资源附件列表，OSS文件的fileUrl会自动转换为完整访问URL
 * @summary 微信端查询业务资源
 */
const listByBiz = (
    params: ListByBizParams,
 ) => {
      return orvalMutator<AjaxResult>(
      {url: `/wx/resource/biz`, method: 'GET',
        params
    },
      );
    }
  return {addSave,listByBiz}};
export type AddSaveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['addSave']>>>
export type ListByBizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof get>['listByBiz']>>>
